name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image for 'Aircrack-ng'
        run: docker build aircrack-ng/. --file Dockerfile --tag my-image-name:$(date +%s)
