name: Docker Compose

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker images
        run: docker-compose build

      - name: Push the Docker images
        if: github.ref == 'refs/heads/master'
        run: docker-compose push
