name: Docker Compose

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 */1 *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker images
        run: docker-compose build

      - name: Login the Docker images on master
        if: github.ref == 'refs/heads/master'
        run: docker login -u mathou54 -p ${{ secrets.DockerToken }}

      - name: Push the Docker images on master
        if: github.ref == 'refs/heads/master'
        run: docker-compose push
